- defaults:
    link:
        force: true
        create: true
        relink: true

- clean: ['~']

- link:
    ~/.bash_profile: bash_profile
    ~/.bash_prompt: bash_prompt
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.ssh/config:
        path: ssh/config
        create: true
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.functions: functions
    ~/.exports: exports
    ~/.aliases: aliases
    ~/.tmux.conf: tmux.conf
    ~/.bitly: bitly

